joshbuddy/jsonpath

- lib/jsonpath.rb
- test/test_jsonpath.rb
This fixes a bug where an unclosed bracket led to infinite loop.
> Detect unmatched brackets

- lib/jsonpath.rb
- test/test_jsonpath.rb
I'd like to propose a method to join paths, i.e. add/concatenate a path to an existing one:
```ruby
JsonPath.new("$.store").join("book..author").on(document)
```
The use case i encounter quite often is: in, e.g. unit tests, i use some kind of base path, and i want to extend it multiple times and for different json documents. As i want to stay DRY i can only concatenate strings. However, a #join method provided by JsonPath would be IMHO much cleaner.
Thanks for your feedback/review.
> Path join feature

- lib/jsonpath/enumerable.rb
- test/test_jsonpath.rb
Now we are able to select nodes like this:
`$.info[?(@.decl.code == 'code1')].values..value` 
So now `@.decl.code` can output upper object out of brackets in any level.
> Added possibility to watch over multiple children nodes in sub query

- Gemfile
- Rakefile
Added simplecov gem to track code coverage.
> add simplecov test coverage

- lib/jsonpath.rb
- test/test_jsonpath.rb
Allows using paths on documents that use sigils to namespace meta data
or common fields such as JSON-LD
> Support '@' and '$' as part of member names

- README.md
- lib/jsonpath.rb
- lib/jsonpath/enumerable.rb
- lib/jsonpath/parser.rb
- lib/jsonpath/version.rb
- test/test_jsonpath.rb
What's left.
```ruby
if pos == (@path.size - 1) && node && allow_eval?
yield_value(blk, context, key) if instance_eval("node #{@path[pos]}")
end
```
> Eliminating the use of eval step by step

- lib/jsonpath/parser.rb
- lib/jsonpath/version.rb
- test/test_jsonpath.rb
Some benchmarks.
```bash
❯ ruby to_f.vs.cast.rb
Warming up --------------------------------------
cast   189.307k i/100ms
cast bad   188.133k i/100ms
to_f    90.466k i/100ms
to_f bad    88.079k i/100ms
Calculating -------------------------------------
cast      5.323M (± 4.8%) i/s -     26.692M in   5.026322s
cast bad      5.271M (± 5.4%) i/s -     26.339M in   5.012467s
to_f      1.274M (± 4.3%) i/s -      6.423M in   5.050091s
to_f bad      1.286M (± 5.7%) i/s -      6.430M in   5.017965s
```
> Fixing checking if operand is a number or not by casting.

- lib/jsonpath/parser.rb
- test/test_jsonpath.rb
The regular expression used when parsing filter expressions would not match on tokens containing an underscore, e.g. `with_underscore`
> Filter with underscore

- lib/jsonpath.rb
- lib/jsonpath/enumerable.rb
- test/test_jsonpath.rb
Sorry for dragging you into this @dblock. 
So, look at this PR. It's a regression fix for the attached issues. Apparently, this logic was correct. I fixed the test which was testing for your regression as well, and a small fix made it work. Apparently to this online parser: http://jsonpath.herokuapp.com/ the top level element needs to be included in order for the match to happen.
There were definitely problems here, but also, it seems that my earlier logic fix to this part: https://github.com/joshbuddy/jsonpath/blob/master/lib/jsonpath/enumerable.rb#L69 was, in fact, correct. The other validator was wrong apparently.
Now all the tests are passing. Please everyone involved check if this is correct.
@NDuggan, @SteveDonie and thank you very much for submitting these issues.
> Regression fixing for issue: #83 #82.

- .travis.yml
- lib/jsonpath/parser.rb
- test/test_jsonpath.rb
Prior to this commit if a nested grouping was encountered (ie. `((this && that) || the_other)` the gem would raise the following error:
```
NoMethodError:
undefined method `strip' for nil:NilClass
```
It appears that in this scenario it's possible that the `operator` variable hasn't yet been set. The proposed fix is simply coercing the variable into a `String` before attempting to call the `#strip` function.
> Fix bug related to nested groupings

- jsonpath.gemspec
- lib/jsonpath/parser.rb
`vendor/bundle/ruby/2.6.0/gems/to_regexp-0.2.1/lib/to_regexp.rb:35: warning: `*' interpreted as argument prefix`
fixes https://github.com/joshbuddy/jsonpath/issues/125
> remove to_regex dependency and the warnings it causes

- README.md
- lib/jsonpath.rb
- lib/jsonpath/dig.rb
- lib/jsonpath/enumerable.rb
- lib/jsonpath/parser.rb
- test/test_jsonpath.rb
- test/test_readme.rb
@Skarlso I restarted my branch with another strategy, but with same goal (support for symbolized keys).
Maybe you need to look at commits in order, but basically:
1. I added some additional tests
2. I refactored some `dig` logic without breaking anything
3. Then and only then I added support for more `dig` scenario and the symbols option
4. I also gave some love to the README (available options) and added unit tests for it
WDYT?
> Factorize `dig` logic ; add a few options ; more tests ; fix README

- lib/jsonpath.rb
- test/test_jsonpath.rb
JSON default allows 100 level deep parsing. If you want to go beyond 100 level we need to configure max_nesting.
Steps for Reproduce: 
Try to Prase 101 level deep hash `JsonPath.new('$.a').on(101_level_deep_hash)` will get above error.
> Add Option to configure max_nesting

- README.md
- jsonpath.gemspec
- lib/jsonpath.rb
- test/test_jsonpath.rb
Fix for issue id : [#126](https://github.com/joshbuddy/jsonpath/issues/126)
> Generate jsonpath list from json 

- lib/jsonpath/parser.rb
- test/test_jsonpath.rb
> bug #147: stop at character '!' when scanning key name, to avoid consuming first char of operator '!='

- Gemfile
It is apparently breaking on a new release of regexp_parser (2.3.1) in the github action bundle step.
> Remove rubocop for now

- README.md
- lib/jsonpath/enumerable.rb
- test/test_jsonpath.rb
https://github.com/joshbuddy/jsonpath/issues/153
When "$" is used as a key in an object, the Enumerator treats it as a root instead of a key inside an object, fixed that by calling `handle_wildecard `  if the given node is not equal to the actual object then it's not a root
Updated readme with the correct function name
> Jsonpath with keyname $ not working

- lib/jsonpath/enumerable.rb
```
JsonPath.on({}, "[*]")
#-> lib/jsonpath/enumerable.rb:88:in `%': divided by 0 (ZeroDivisionError)
```
Greetings, I got an error as above and I fixed it in this pr.
this happens when node size is zero in jsonpath enumerable.
```
start_idx %= node.size
end_idx %= node.size
```
> skip when node size is zero

- .github/workflows/test.yml
- lib/jsonpath/enumerable.rb
- test/test_jsonpath.rb
Fix for issue id : [#143](https://github.com/joshbuddy/jsonpath/issues/143)
With this PR, test coverage is added for Ruby 3.0, 3.1, and 3.2.
> To filter elements of an array with unknown name / Add ruby versions for test cases

- lib/jsonpath.rb
- test/test_jsonpath.rb
Fix for https://github.com/joshbuddy/jsonpath/issues/141
setting max_nesting to false when max_nesting is greater than 100
> Fix issue #141: nesting of 101 too deep

- lib/jsonpath.rb
- test/test_jsonpath.rb
see: https://ruby-doc.org/3.0.6/Regexp.html#class-Regexp-label-Character+Properties
fixes joshbuddy/jsonpath#163
> Update member name regexp to support UTF8 alphanumeric characters

- lib/jsonpath.rb
- test/test_jsonpath.rb
Currently it uses a symbolize_keys send in the on options, and ignore if its sent during the initialization.
So in this PR using this params send during initialization as fallback option.
Means first checking if _**on**_  params has symbolize_keys, else checking in opts send during the initialization.
> #162 : symbolize_keys option doesn't work as the README says
